In [13]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [14]:
file_name = 'forestfires.csv'
df = pd.read_csv(file_name)
#print(df.columns)
df.head(5)

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [15]:
print(df.shape)

(517, 13)


In [16]:
print(len(df))
df = df.sample(n=200)
print(len(df))

517
200


In [17]:
a = df.values
print(a[:3])


[[7 4 'oct' 'fri' 90.0 41.5 682.6 8.7 11.3 60 5.4 0.0 0.0]
 [4 5 'aug' 'wed' 95.2 217.7 690.0 18.0 23.4 49 5.4 0.0 6.43]
 [8 6 'aug' 'sat' 89.4 253.6 768.4 9.7 14.2 73 2.7 0.0 0.0]]


In [18]:
print(a.shape)
n = a.shape[1]
print(n)
y = a[:,[n-1]]
print(y.shape)

(200, 13)
13
(200, 1)


In [19]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
y = LE.fit_transform(y)
print(y[:10])
print(len(y))
y1 = y[y==1]
print(len(y1))
y0 = y[y==0]
print(len(y0))

[ 0 57  0 63  0  0 77 34  0 11]
200
1
94


/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [20]:
X = a[:,:-1]
print(X[:3])
print(X.shape)
X= X[:,:]
print(X.shape)

[[7 4 'oct' 'fri' 90.0 41.5 682.6 8.7 11.3 60 5.4 0.0]
 [4 5 'aug' 'wed' 95.2 217.7 690.0 18.0 23.4 49 5.4 0.0]
 [8 6 'aug' 'sat' 89.4 253.6 768.4 9.7 14.2 73 2.7 0.0]]
(200, 12)
(200, 12)


In [21]:
b = df.select_dtypes(include=['float64','int64'])
print(b.shape)
print(b)
X = b.values
print(X.shape)
print(X[:3])

(200, 11)
     X  Y  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
37   7  4  90.0   41.5  682.6   8.7  11.3  60   5.4   0.0  0.00
450  4  5  95.2  217.7  690.0  18.0  23.4  49   5.4   0.0  6.43
437  8  6  89.4  253.6  768.4   9.7  14.2  73   2.7   0.0  0.00
187  1  5  90.9  126.5  686.5   7.0  21.0  42   2.2   0.0  7.30
447  3  4  93.4   17.3   28.3   9.9   8.9  35   8.0   0.0  0.00
..  .. ..   ...    ...    ...   ...   ...  ..   ...   ...   ...
441  8  6  92.1  207.0  672.6   8.2  25.5  29   1.8   0.0  1.23
52   4  3  92.1  111.2  654.1   9.6  20.4  42   4.9   0.0  0.00
333  1  4  92.1   87.7  721.1   9.5  18.1  54   3.1   0.0  2.13
84   1  2  91.7  114.3  661.3   6.3  20.2  45   3.6   0.0  0.00
495  6  6  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0  0.00

[200 rows x 11 columns]
(200, 11)
[[  7.     4.    90.    41.5  682.6    8.7   11.3   60.     5.4    0.
    0.  ]
 [  4.     5.    95.2  217.7  690.    18.    23.4   49.     5.4    0.
    6.43]
 [  8.     6.    89.4  253.

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
print(X)


[[0.75       0.28571429 0.86462882 ... 0.55555556 0.         0.        ]
 [0.375      0.42857143 0.97816594 ... 0.55555556 0.         0.00589454]
 [0.875      0.57142857 0.85152838 ... 0.25555556 0.         0.        ]
 ...
 [0.         0.28571429 0.91048035 ... 0.3        0.         0.00195262]
 [0.         0.         0.90174672 ... 0.35555556 0.         0.        ]
 [0.625      0.57142857 1.         ... 0.2        0.         0.        ]]


In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)
print(X_train.shape, y_train.shape)
print(X_test.shape,y_test.shape)

(160, 11) (160,)
(40, 11) (40,)


In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model = model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(y_pred)
acc_score = metrics.accuracy_score(y_pred,y_test)
print('accuracy:\n', acc_score)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
accuracy:
 0.4
